baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Mockery of the Arts'

[module]
[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"
disable = false

[menu]

[[menu.social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[menu.social.params]
icon = "brand-twitter"

[params]

[[params.widgets.homepage]]
type = "categories"

[[params.widgets.page]]
type = "toc"